version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # correctness / bugs
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

    # useful, low-noise extras for a CLI + local storage project
    - unconvert
    - errorlint
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: exported
      - name: error-strings
      - name: error-naming
      - name: var-naming
      - name: early-return

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
